#!/bin/python3

from pathlib import Path
from os import EX_OK, EX_CONFIG
from git import Repo


def get_repository():
    return Repo(Path().resolve(), search_parent_directories=True)


def check_production_branch(repo):
    PRODUCTION_BRANCHES = ["main", "develop", "master"]
    active_branch = repo.active_branch.name.strip()
    for branch in PRODUCTION_BRANCHES:
        if active_branch.__eq__(branch):
            exit(EX_CONFIG)


def main():
    repo = get_repository()
    check_production_branch(repo)
    exit(EX_OK)


if __name__ == '__main__':
    main()
